# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98194162826c576cb78176e3c79cfcb578a428fe34406652ab69a934cdf4c2c2cd83dc82e613243844d6ec23a706852f81e635ddc6f98dae4bb7baa5cc0665c6

test:
  secret_key_base: 32a3393713dd1f109905df486b546567d15dd5b51f4c9891c9d22edbdee25cca4ddd98c9314047032cf9c7adb949f696a1dfc0d0a5bf53704fa757683f50d913

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
